site_name: ifk-storm-water-management
repo_url: https://github.com/Ingenjorsarbete-For-Klimatet/ifk-storm-water-management
site_author: IFK
site_url: https://ingenjorsarbete-for-klimatet.github.io/ifk-storm-water-management/
repo_name: Ingenjorsarbete-For-Klimatet/ifk-storm-water-management

nav:
- Home: index.md

watch:
- src

theme:
  name: material
  custom_dir: material
  palette:
    scheme: default
    primary: black
    accent: light green
  language: en
  icon:
    repo: fontawesome/brands/git-alt
  logo: assets/ifk_logo_white.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs

plugins:
- search
- mkdocstrings

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
